plugins {
    id 'com.android.application'
}

android {
    namespace 'com.xiaoma.daily'
    compileSdk 35

    defaultConfig {
        applicationId 'com.xiaoma.daily'
        minSdk 24
        targetSdk 35
        versionCode 1
        versionName '0.1.0'
    }
    buildFeatures {
        viewBinding true
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    testImplementation 'junit:junit:4.13.2'
}
